project:
  output-dir: report/html

toc: true
number-sections: true

format:
  html:
#    css: styles.css
    html-math-method: mathjax
    code-tools:
      source: https://github.com/MRC-CSO-SPHSU/financial_distress
      toggle: true
    code-fold: true
  pdf:
    latex-engine: xelatex
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
  docx:
    reference-doc: template.docx
    number-sections: true
    margin-left: 3cm
    margin-right: 3cm